version: "3.9"

services:
  influxdb:
    image: influxdb:2.2.0-alpine
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
      - "2003:2003"
    volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/influxdb/data
      - ./data/influxdb:/var/lib/influxdb2      
    networks:
      - network1

  grafana:
    image: grafana/grafana:8.5.3
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - './env/env.grafana'
    user: "0"
    links:
      - influxdb    
    networks:
      - network1

networks:
  network1: